#!/bin/bash
# Docker'ı yükleyin
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce

# Hashtopolis için Dockerfile oluşturun
cat << EOF > Dockerfile
FROM ubuntu:latest
RUN apt-get update && apt-get install -y apache2 php php-mysql libapache2-mod-php wget unzip
RUN wget https://github.com/hashtopolis/server/archive/refs/heads/master.zip \
    && unzip master.zip -d /var/www/ \
    && mv /var/www/server-master /var/www/hashtopolis \
    && rm master.zip
RUN echo '<VirtualHost *:80>\n\
    ServerAdmin webmaster@localhost\n\
    DocumentRoot /var/www/hashtopolis\n\
    ErrorLog \${APACHE_LOG_DIR}/error.log\n\
    CustomLog \${APACHE_LOG_DIR}/access.log combined\n\
    <Directory /var/www/hashtopolis>\n\
        AllowOverride All\n\
    </Directory>\n\
    Alias "/hashtopolis" "/var/www/hashtopolis"\n\
</VirtualHost>' > /etc/apache2/sites-available/hashtopolis.conf
RUN a2ensite hashtopolis
RUN a2dissite 000-default
RUN service apache2 restart
EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]
EOF

# Docker imajını oluşturun ve konteyneri başlatın
sudo docker build -t hashtopolis-image .
sudo docker run -d --name hashtopolis-container -p 80:80 hashtopolis-image

echo "Hashtopolis Docker konteyneri başlatıldı ve 80 numaralı port üzerinden erişilebilir."
