#!/bin/bash

# Kullanıcıdan Alınan Bilgiler
MINIO_ROOT_USER="cyrix"
MINIO_ROOT_PASSWORD="AdminPass"
ELASTIC_PASSWORD="AdminPass"
OPENCTI_ADMIN_EMAIL="posta@istanify.com"
OPENCTI_ADMIN_PASSWORD="AdminPass"
OPENCTI_TOKEN=$(uuidgen) # Bu komut otomatik olarak bir UUID oluşturur.

# Sistem Güncellemesi ve Gerekli Paketlerin Kurulumu
echo "Sistem güncellemeleri ve gerekli paketlerin kurulumu yapılıyor..."
sudo apt-get update && sudo apt-get upgrade -y

# Node.js ve Yarn Kurulumu
if ! command -v node >/dev/null 2>&1; then
    echo "Node.js kuruluyor..."
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install -y nodejs
else
    echo "Node.js zaten kurulu."
fi

if ! command -v yarn >/dev/null 2>&1; then
    echo "Yarn kuruluyor..."
    npm install --global yarn
else
    echo "Yarn zaten kurulu."
fi

# Python3-pip ve Diğer Bağımlılıkların Kurulumu
echo "Python3-pip ve diğer bağımlılıkların kurulumu yapılıyor..."
sudo apt-get install -y python3-pip redis-server rabbitmq-server

# RabbitMQ Yönetim Plugin'inin Etkinleştirilmesi
echo "RabbitMQ yönetim plugin'i etkinleştiriliyor..."
sudo rabbitmq-plugins enable rabbitmq_management

# Elasticsearch Kurulumu ve Yapılandırılması
echo "Elasticsearch kurulumu ve yapılandırılması yapılıyor..."
if ! service --status-all | grep -Fq 'elasticsearch'; then
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
    sudo apt-get update && sudo apt-get install -y elasticsearch
    sudo systemctl start elasticsearch
    sudo systemctl enable elasticsearch
else
    echo "Elasticsearch zaten kurulu."
fi

# MinIO Kurulumu
echo "MinIO kurulumu yapılıyor..."
if ! command -v minio >/dev/null 2>&1; then
    wget https://dl.min.io/server/minio/release/linux-amd64/minio
    chmod +x minio
    sudo mv minio /usr/local/bin/
    mkdir -p ~/minio-data
else
    echo "MinIO zaten kurulu."
fi

# OpenCTI Platformunun Kurulumu
echo "OpenCTI platformunun kurulumu yapılıyor..."
if [ ! -d "opencti" ]; then
    git clone https://github.com/OpenCTI-Platform/opencti.git
    cd opencti || exit
    git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
    yarn install
    yarn build
else
    echo "OpenCTI zaten klonlandı."
    cd opencti || exit
fi

# Güvenlik Duvarı Ayarları
echo "Güvenlik duvarı ayarları yapılandırılıyor..."
sudo ufw allow 80/tcp
sudo ufw allow 22/tcp
echo "Güvenlik duvarı kuralları ayarlandı."

# OpenCTI .env dosyası oluşturma ve başlatma
echo "OpenCTI .env dosyası oluşturuluyor ve servis başlatılıyor..."
cat <<EOF >.env
OPENCTI_ADMIN_EMAIL=$OPENCTI_ADMIN_EMAIL
OPENCTI_ADMIN_PASSWORD=$OPENCTI_ADMIN_PASSWORD
OPENCTI_TOKEN=$OPENCTI_TOKEN
EOF

echo "OpenCTI başlatılıyor..."
yarn serve
