#!/bin/bash

# Kullanıcı tanımlı bilgiler
MINIO_ROOT_USER="MinIO_Root"
MINIO_ROOT_PASSWORD="Password"
ELASTIC_PASSWORD="Password"
OPENCTI_ADMIN_EMAIL="admin@istanify.com"
OPENCTI_ADMIN_PASSWORD="Password"
OPENCTI_TOKEN=$(uuidgen) # OpenCTI için bir UUID oluşturur.
RELEASE_VERSION="5.12.29"

# Gerekli bağımlılıkların kurulumu
echo "Gerekli bağımlılıklar kuruluyor..."
sudo apt-get update
sudo apt-get install -y build-essential nodejs npm python3 python3-pip python3-dev

# Elasticsearch Kurulumu
echo "Elasticsearch Kurulumu..."
sudo apt-get install -y elasticsearch
sudo systemctl start elasticsearch
sudo systemctl enable elasticsearch

# Redis Kurulumu
echo "Redis Kurulumu..."
sudo apt-get install -y redis-server
sudo systemctl start redis-server
sudo systemctl enable redis-server

# RabbitMQ Kurulumu
echo "RabbitMQ Kurulumu..."
sudo apt-get install -y rabbitmq-server
sudo systemctl start rabbitmq-server
sudo systemctl enable rabbitmq-server

# MinIO Kurulumu
echo "MinIO Kurulumu..."
wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
sudo mv minio /usr/local/bin/
mkdir -p ~/minio-data
export MINIO_ROOT_USER=$MINIO_ROOT_USER
export MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
minio server ~/minio-data --address :9000 &

# OpenCTI İndirme ve Kurulumu
echo "OpenCTI İndirme ve Kurulumu..."
wget "https://github.com/OpenCTI-Platform/opencti/releases/download/$RELEASE_VERSION/opencti-release-$RELEASE_VERSION.tar.gz"
tar xvfz opencti-release-$RELEASE_VERSION.tar.gz
cd opencti
cp config/default.json config/production.json

# OpenCTI yapılandırma dosyasının güncellenmesi
# Burada, ElasticSearch, Redis, RabbitMQ ve MinIO/S3 yapılandırma detaylarınızı ekleyin.
sed -i "s|\"admin@opencti.io\"|\"$OPENCTI_ADMIN_EMAIL\"|g" config/production.json
sed -i "s|\"ChangeMe\"|\"$OPENCTI_ADMIN_PASSWORD\"|g" config/production.json
sed -i "s|\"ChangeMe\"|\"$OPENCTI_TOKEN\"|g" config/production.json

# Python bağımlılıklarının kurulumu
cd src/python
pip3 install -r requirements.txt

# Ana dizine geri dönme ve OpenCTI'nin başlatılması
cd ../..
yarn install
yarn build
yarn serv

echo "OpenCTI başarıyla kuruldu ve yapılandırıldı."
